### ISSUE TITLE
Cpython error on fcos_core build

### ISSUE THREAD

**Issue by heng2j** [vov-net/VoVNet-FCOS#1]
Hi @stigma0617 .

I noticed that this implementation is still utilizing the code from maskrcnn_benchmark but you created a fcos core version of maskrcnn_benchmark that leave only the fcos related component.

    cd ../VoVNet-FCOS/
    python setup.py build develop
    ....
    Finished processing dependencies for fcos==0.1.9

However, after I rebuilt successfully with the above commands. When I tired to train with my own dataset. I encountered Cpython error.

> ImportError: ../VoVNet-FCOS/fcos_core/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

Can you advise?

**Comment by stigma0617** [comment]
Please refer to this [issue](https://github.com/tianzhi0549/FCOS/issues/69).

If this problem is not resolved, please reopen this issue.
