### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by LIUhansen** [vov-net/VoVNet-FCOS#3]
I cann't get paraments of the Fcos_V_39xxx  from China. Can you show me how to train from random initialization?

**Comment by huangzicheng** [comment]
> I cann't get paraments of the Fcos_V_39xxx from China. Can you show me how to train from random initialization

you must use VPN to download,give me your e-mail, I'll send to you.

**Comment by LIUhansen** [comment]
That's great. 
15697891287@163.com

Thanks !
